webinterface_linux/webinterface/tula/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'tula'
urlpatterns = [
    path('', views.HomeView, name='home'),
    path('edit/<file_name>', views.editview, name='edit'),
    path('edit_rejected/<file_name>', views.editview_rejected, name='edit_rejected'),
    path('switch/<file_name>', views.switch, name='switch'),
    path('switch_rejected/<file_name>', views.switch_rejected, name='switch_rejected'),
    path('train/', views.TrainView, name='train'),
    path('real_time_view/', views.RealTimeView, name='real_time_view'),
    path('real_time_view/topframe', views.TopFrameView, name='topframe'),
    path('real_time_view/bottomframe', views.BottomFrameView, name='bottomframe'),
    path('accepted_list/', views.accepted_list, name='accepted_list'),
    path('rejected_list/', views.rejected_list, name='rejected_list'),
    path('list_choice/', views.list_choice, name='list_choice'),
    path('real_time_view/recent', views.recent, name='recent'),
]

webinterface_linux/webinterface/webinterface/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('tula/', include('tula.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webinterface_linux/webinterface/tula/models.py
import datetime

from django.db import models
from django.utils import timezone

class File(models.Model):
	file_name = models.CharField(max_length=200)
	status = models.CharField(max_length=200)
	def __str__(self):
		return self.file_name
	def create(file_n,stat):
		f = File(file_name=file_n,status=stat)
		f.save()

webinterface_linux/webinterface/tula/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import File
import os, shutil
from os.path import join

def TrainView(request):
	template_name = 'tula/train.html'
	return render(request, 'tula/train.html')

def TopFrameView(request):
	template_name = 'tula/topframe.html'
	return render(request, 'tula/topframe.html')

def BottomFrameView(request):
	template_name = 'tula/bottomframe.html'
	return render(request, 'tula/bottomframe.html')

def RealTimeView(request):
	template_name = 'tula/real_time_view.html'
	return render(request, 'tula/real_time_view.html')

def HomeView(request):
	template_name = 'tula/home.html'
	return render(request, 'tula/home.html')

def list_choice(request):

	File.objects.all().delete()
	selected_choice = request.POST['status']

	if selected_choice == 'accepted':
		return HttpResponseRedirect('/tula/accepted_list/')
	elif selected_choice == 'rejected': 		
		return HttpResponseRedirect('/tula/rejected_list/')


def accepted_list(request):
	#File.objects.all().delete()
	#for files in os.listdir('C:\\Users\\Roberto.Oliveira\\Desktop\\sapec_interface\\mysite\\media\\images\\accepted'):
	for files in os.listdir('media/images/accepted'):
			f = File.objects.filter(file_name = files,status='accepted')
			if len(f) > 0:
				continue
				#print('Imagem já existe')
			else:
				if "chart" not in files:
					File.create(files,'accepted')
				#print('Imagem não existe!')
	files = File.objects.filter(status='accepted')
	return render(request, 'tula/results.html', {'files': files})

def rejected_list(request):
	#for files in os.listdir('C:\\Users\\Roberto.Oliveira\\Desktop\\sapec_interface\\mysite\\media\\images\\rejected'):
	for files in os.listdir('media/images/rejected'):
			f = File.objects.filter(file_name = files,status='rejected')

			if len(f) > 0:
				continue
				#print('Imagem já existe')
			else:
				if "chart" not in files:
					File.create(files,'rejected')
				#print('Imagem não existe!')
	files = File.objects.filter(status='rejected')
	return render(request, 'tula/results_rejected.html', {'files': files})	


def recent(request):
	string = "python3 image_get.py"
	os.system(string)
	files = os.listdir('media/images/recent')
	if files[0][9] == '1':
		file_status = 'Rejected'
	else:
		file_status = 'Accepted'
	return render(request, 'tula/bottomframe.html', {'file': files[0] , 'file_status':file_status})	

def editview(request,file_name):
	print(file_name)
	return render(request, 'tula/edit.html', {'file_name': file_name})

def editview_rejected(request,file_name):
	print(file_name)
	return render(request, 'tula/edit_rejected.html', {'file_name': file_name})


def switch(request,file_name):
	f = File.objects.filter(file_name=file_name)
	#print(f)
	f.update(status='rejected')
	#shutil.move('C:\\Users\\Roberto.Oliveira\\Desktop\\sapec_interface\\mysite\\media\\images\\accepted\\'+file_name,'C:\\Users\\Roberto.Oliveira\\Desktop\\sapec_interface\\mysite\\media\\images\\rejected\\')
	string = "python3 imgclassifier0.1.py media/images/accepted/" + file_name +" 1"
	print('Executed "',string, '"to REJECT image')
	os.system(string)
	#print(file_name)
	return HttpResponseRedirect('/tula/accepted_list/')


def switch_rejected(request,file_name):
	f = File.objects.filter(file_name=file_name)
	#print(f)
	f.update(status='accepted')
	#shutil.move('C:\\Users\\Roberto.Oliveira\\Desktop\\sapec_interface\\mysite\\media\\images\\rejected\\'+file_name,'C:\\Users\\Roberto.Oliveira\\Desktop\\sapec_interface\\mysite\\media\\images\\accepted\\')
	string = "python3 imgclassifier0.1.py media/images/rejected/" + file_name +" 0"
	print('Executed "',string, '"to ACCEPT image')
	os.system(string)
	#print(file_name)
	return HttpResponseRedirect('/tula/rejected_list/')

webinterface_linux/webinterface/tula/templates/tula/base.html
<!doctype html>
{% load static %}
<html>
	<head>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{% static 'tula/style.css' %}">
		<div>
			<h1> Tula Intelligent Interface</h1>
		</div>
		<div class = container>
			<div style ='float:left'>
				<form action="{% url 'tula:home'%}" method="post" target="_top">
					{% csrf_token %}
				    <input type="submit" value="Início" />
				</form>
			</div>
			<div style = 'float:left;'>
				<form action="{% url 'tula:real_time_view'%}" method="post"  target="_top">
					{% csrf_token %}
				    <input type="submit" value="Ver Câmara" />
				</form>
			</div>
			<div style = 'float:left;'>
				<form action="{% url 'tula:train'%}" method="post" target="_top">
					{% csrf_token %}
				    <input type="submit" value="Treinar Modelo" />
				</form>
			</div>
		</div>
	<title>TII</title>
	</head>


	<body>
		<div>	
			{% block content %}
			{% endblock %}
		</div>
	</body>

	<div id="footer">
	<img src="{% static "tula/tula_logo.png" %}" alt="My image">	
	</div>
</html>

webinterface_linux/webinterface/tula/templates/tula/bottomframe.html
{% load static %}
<html>
<header><title>This is title</title></header>
<body> 


<div style="float: left;">
	<script type="text/javascript">
		document.write('<p style="margin-left:75%; margin-top:50px;"><img src="/media/images/recent/{{file}}?'+Math.random()+' alt="Willmaster.com logo" border="0" height="500" width="500"></p>');
	</script>
</div>
<div style = "float: right;margin-top:270px;margin-right:35%;">
	<div>
		Ficheiro: {{file}} 
	</div>
	<div>
		{%if file_status == "Rejected" %}
			Status: Imagem foi <font color="red">REJEITADA</font> pelo classificador
		{%elif file_status == "Accepted" %}
			Status: Imagem foi <font color="green">ACEITE</font> pelo classificador
		{% endif %}
	</div>
</div>
</body>
</html>

webinterface_linux/webinterface/tula/templates/tula/edit.html
<!DOCTYPE html>
{% extends 'tula/base.html' %}
{% block content %}
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        <!-- List of uploaded files -->
        <div id= "container3">
        <div>
        	<script type="text/javascript">
                     document.write('<p style="margin-left:25%; margin-top:5px;float:left;"><img src="/media/images/accepted/{{file_name}}?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="500" width="500"></p>');
                     document.write('<p style="margin-left:10%; margin-top:5px;"><img src="/media/images/accepted/{{file_name}}chart.png?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="500" width="500"></p>');
                     </script>
        </div>
        <!-- Upload form. Note enctype attribute! -->

        <div class = container4>
			<div>
				<form action="{% url 'tula:switch' file_name%}" method="post">
					{% csrf_token %}
					<input type="submit" value="REJEITAR" />
				</form>
			</div>
			<div>
				 <form action="{% url 'tula:accepted_list'%}" method="post">
	            {% csrf_token %}
	            <input type="submit" value="Voltar" />
	        </form>
			</div>
		</div>
        </div>
    </body>

</html>
{% endblock %}

webinterface_linux/webinterface/tula/templates/tula/edit_rejected.html
<!DOCTYPE html>
{% extends 'tula/base.html' %}
{% block content %}
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        <!-- List of uploaded files -->
        <div id= "container3">
        <div>
        	<script type="text/javascript">
                     document.write('<p style="margin-left:25%; margin-top:5px;float:left;"><img src="/media/images/rejected/{{file_name}}?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="500" width="500"></p>');
                     document.write('<p style="margin-left:10%; margin-top:5px;"><img src="/media/images/rejected/{{file_name}}chart.png?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="500" width="500"></p>');
                     </script>
        </div>
        <!-- Upload form. Note enctype attribute! -->
        <div class = container4>
			<div>
				<form action="{% url 'tula:switch_rejected' file_name%}" method="post">
				{% csrf_token %}
				<input type="submit" value="ACEITAR" />
			</form>
			</div>
			<div>
				 <form action="{% url 'tula:rejected_list'%}" method="post">
		            {% csrf_token %}
		            <input type="submit" value="Voltar" />
	        </form>
			</div>
		</div> 
        </div>       
    </body>

</html>
{% endblock %}

webinterface_linux/webinterface/tula/templates/tula/home.html
{% extends 'tula/base.html' %}
{% block content %}


	<h3>Bem-Vindo à Tula Intelligent Interface</h3>


{% endblock %}

webinterface_linux/webinterface/tula/templates/tula/real_time_view.html
<html>
  <head>
   <script type="text/javascript">
      window.onload = setupRefresh;
 
      function setupRefresh() {
          setInterval("refreshFrame();", 1500);
      }
      function refreshFrame() {
         parent.right_frame.location.reload();
      }
  </script>
  </head>
  <frameset id="cntfrm" rows="20%,*">
  	<frame name="left_frame" src="topframe" scrolling="auto" />
  	<frame  name="right_frame" scrolling="auto" src="recent" />
  </frameset>



</html>
 

webinterface_linux/webinterface/tula/templates/tula/results.html
{% extends 'tula/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        <!-- List of uploaded files -->
        <div id= "container3">
        <form action="{% url 'tula:train'%}" method="post">
            {% csrf_token %}
            <input type="submit" value="Voltar" />
        </form>
        {% if files %}
            <ul>
                {% for document in files %}
                     <script type="text/javascript">
                     document.write('<img src="/media/images/accepted/{{document.file_name}}?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="200" width="200">');
                     document.write('<img src="/media/images/accepted/{{document.file_name}}chart.png?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="200" width="200">');
                     </script>
                   <li><a href="{% url 'tula:edit' document.file_name %}"> FILE: {{document.file_name}} | STATUS: {{document.status }}</a></li>
                        <form action="{% url 'tula:switch' document.file_name%}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="REJEITAR" />
                        </form>
                {% endfor %}
                <form action="{% url 'tula:train'%}" method="post">
                {% csrf_token %}
                <input type="submit" value="Voltar" />
            </ul>
        {% else %}
            <p>No files.</p>
            <form action="{% url 'tula:train'%}" method="post">
            {% csrf_token %}
            <input type="submit" value="Voltar" />
        {% endif %}
        </div>
        <!-- Upload form. Note enctype attribute! -->
        
    </body>

</html>
{% endblock %}

webinterface_linux/webinterface/tula/templates/tula/results_rejected.html
<!DOCTYPE html>
{% extends 'tula/base.html' %}
{% block content %}
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        <!-- List of uploaded files -->
        <div id= "container3">
        <form action="{% url 'tula:train'%}" method="post">
            {% csrf_token %}
            <input type="submit" value="Voltar" />
        </form>
        {% if files %}
            <ul>
                {% for document in files %}
                     <script type="text/javascript">
                     document.write('<img src="/media/images/rejected/{{document.file_name}}?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="200" width="200">');
                     document.write('<img src="/media/images/rejected/{{document.file_name}}chart.png?'+Math.random()+'" alt="Willmaster.com logo" border="0" height="200" width="200">');
                     </script>
                   <li><a href="{% url 'tula:edit_rejected' document.file_name %}"> FILE: {{document.file_name}}   |   STATUS:{{document.status }}</a></li>
                   <form action="{% url 'tula:switch_rejected' document.file_name%}" method="post">
                        {% csrf_token %}
                    <input type="submit" value="ACEITAR" />
                    </form>
                {% endfor %}
                <form action="{% url 'tula:train'%}" method="post">
                {% csrf_token %}
                <input type="submit" value="Voltar" />

            </ul>
        {% else %}
            <p>No files.</p>
            <form action="{% url 'tula:train'%}" method="post">
            {% csrf_token %}
            <input type="submit" value="Voltar" />
        {% endif %}
    	</div>
        <!-- Upload form. Note enctype attribute! -->
        
    </body>

</html>
{% endblock %}

webinterface_linux/webinterface/tula/templates/tula/topframe.html
{% load static %}
<html>
	<head>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{% static 'tula/style.css' %}">
		<div>
			<h1> Tula Intelligent Interface</h1>
		</div>
		<div class = container>
			<div style ='float:left'>
				<form action="{% url 'tula:home'%}" method="post" target="_top">
					{% csrf_token %}
				    <input type="submit" value="Início" />
				</form>
			</div>
			<div style = 'float:left;'>
				<form action="{% url 'tula:real_time_view'%}" method="post"  target="_top">
					{% csrf_token %}
				    <input type="submit" value="Ver Câmara" />
				</form>
			</div>
			<div style = 'float:left;'>
				<form action="{% url 'tula:train'%}" method="post" target="_top">
					{% csrf_token %}
				    <input type="submit" value="Treinar Modelo" />
				</form>
			</div>
		</div>
	<title>TII</title>
	</head>
<body>
<h2>Monitorização em tempo real</h2>
</body>
</html>

webinterface_linux/webinterface/tula/templates/tula/train.html
{% extends 'tula/base.html' %}
{% block content %}
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h2> Escolher classificações a observar: </h2>
<form action="{% url 'tula:list_choice' %}" method="post">
{% csrf_token %}
	<div class = container2>
		  <input type="radio" name="status" value="accepted" checked> Aceites<br>
		  <input type="radio" name="status" value="rejected"> Rejeitadas<br>
	<input type="submit" value="OK" />
	</div>
</form>
{% endblock %}